### ISSUE TITLE
Transformar bubble do Mapa em conteudo retirado do WordPress

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/redeartesol-mapa#1]
Transformar o bubble em conteúdo retirado do user profile
- Avatar
- Bio
- Endereço
- Email
- Telefone

Retirar campos inuteis do user profile como "AOL messenger", e outras coisa assim, vai ajudar muito na usabilidade.

Ai precisamos acrescentar aquele campo para colocar a URL do "Leia Mais", com classes do Odin ou com ACF, o que for melhor para você

**Comment by matheusgimenez** [comment]
feito no ultimo commit
