### ISSUE TITLE
Mais campos no User Profile - O que deve ir para o Bubble está indicado *

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/redeartesol-mapa#2]
Ei Matheus,

Preciso de mais campos no Profile, veja as telas abaixo:

![cidada-estado](https://cloud.githubusercontent.com/assets/3632627/6928471/a241b7ea-d7ca-11e4-96a3-5fb648b8d70c.png)
- um campo simples Cidade/Estado

![tipo-de-artesao](https://cloud.githubusercontent.com/assets/3632627/6928482/b02a1168-d7ca-11e4-9f18-0e9f14a2067c.png)
- Um seletor de Tipo de Artesão: Associação, Artesão Individual, Indígena, Mestre
  Lembrando que isso aqui um dia vai virar um "categoria" filtravel do mapa. Isso deve estar no Bubble*
- Um seletor de Região: Norte, Nordeste, Centro-Oeste, Sudeste e Sul.

![regiao](https://cloud.githubusercontent.com/assets/3632627/6928573/522c3ae0-d7cb-11e4-9fdd-dc642dd53d9e.png)

AI tem uma questão de Tipologia que vai entrar como lista seletora tb, mas elas serão um CPT do mapa... vou fazer primeiro uma issue desse CPT e depois faço outra para essa lista vir para cá, de forma dinâmica. Isso estará no Bubble tb..

**Comment by matheusgimenez** [comment]
feito no ultimo commit
